version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "9896:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - html:/usr/share/nginx/html
    depends_on:
      - fetcher

  fetcher:
    build:
      context: .
      dockerfile: Dockerfile.fetcher
    environment:
      - APK_REPOSITORY_URL=http://mirrors.ustc.edu.cn/alpine/v3.14/main
      - REPO_URL=https://github.com/trebleC/MusicBlog.git
      - TARGET_DIR=/usr/src/app/html
    volumes:
      - html:/usr/src/app/html

volumes:
  html:
